name: Deploy staging
on:
  push:
    tags:
      # Matches stable and pre-releases
      - "[0-9]+.[0-9]+.[0-9]+*"
    branches:
      # Matches release branches
      - "[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      git_ref:
        description: Git ref (tag, branch or commit hash) to deploy
        required: true
      trigger_release:
        type: boolean
        description: "Trigger release"
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      VERSION: ${{ github.event.inputs.git_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.VERSION }}

      - name: Set custom version
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        # Add commit hash to basic version number
        run: |
          set -x
          hash=$(git rev-parse --short HEAD)
          echo "CUSTOM_VERSION=${VERSION}-${hash}" >> $GITHUB_ENV

      - name: Echo
        run: |
          set -x
          echo VERSION=${VERSION}
          echo CUSTOM_VERSION=${CUSTOM_VERSION}
          echo github_ref=${{ github.ref }}

      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.event.inputs.trigger_release == 'true' }}
        run: |
          echo "Releasing ..."


